language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t karthikmrtce/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true karthikmrtce/docker-react npm run test -- --coverage
